version: "2"
linters:
  # Disable all linters.
  # Default: false
  default: none
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - errorlint
    - exptostd
    - gocritic
    - godot
    - importas
    - intrange
    - nolintlint
    - perfsprint
    - sloglint
    - usestdlibvars
    - usetesting
formatters:
  enable:
    - gofmt
